[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
  [context.deploy-preview.environment]

# Add build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
