[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  NODE_ENV = "development"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_LIFECYCLE_DEBUG = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_CONFIG_UNSAFE_PERM = "true"
  NPM_CONFIG_PREFER_OFFLINE = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  NPM_CONFIG_PROGRESS = "false"
  NPM_CONFIG_LOGLEVEL = "error"
  NPM_CONFIG_ENGINE_STRICT = "true"
  NPM_CONFIG_SAVE = "true"
  NPM_CONFIG_SAVE_DEV = "true"
  NPM_CONFIG_SAVE_OPTIONAL = "true"
  NPM_CONFIG_SAVE_PEER = "false"
  PRISMA_GENERATE_SKIP_POSTINSTALL = "true"

[context.production]
  command = "npm install && npm run build"
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm install && npm run build"
  NODE_ENV = "development"
  NPM_CONFIG_SAVE_BUNDLE = "false"
  NPM_CONFIG_SAVE_PREFIX = ""
  NPM_CONFIG_SAVE_EXACT = "true"
  NPM_CONFIG_SAVE_PRODUCTION = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Production context
[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
  [context.production.environment]
    NODE_ENV = "production"

# Development context (for branch deploys)
[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  
  [context.deploy-preview.environment]
    NODE_ENV = "development"

# Add build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
